const H = require('./helpers');
const { bodyP: p, tituloSeccion: S, tituloPrincipal: T } = H;

module.exports = [
  S('7. Indicadores sociales y ambientales'),
  p('El checklist del módulo pide declarar qué indicadores sociales y ambientales va a considerar el modelo. Antes de enumerarlos corresponde dejar constancia de dos cosas. La primera es que **Scala no pertenece al vertical de negocios de impacto**, de modo que la consigna sobre cómo el producto previene, mejora, compensa o resuelve un problema social o ambiental no le aplica en el sentido estricto en que se le exige a ese vertical. La segunda es que **la consigna sobre sinergias y modificaciones con un modelo de negocios existente tampoco aplica**, porque es la consigna de intrapreneurship y Scala es una empresa nueva, sin estructura previa a la que adaptarse. Dicho eso, el modelo sí tiene efectos sociales medibles, y se van a seguir cuatro familias de indicadores desde la primera cohorte.'),
  p('**Acceso a la guía experta.** El efecto social más directo es de precio: un entrenador online cuesta entre US$150 y US$250 por mes, y el Módulo 3 encontró que el 63% de los atletas amateurs gasta cero hoy en asesoramiento. Los indicadores son el precio relativo a la alternativa humana, hoy entre una quinceava y una vigesimoquinta parte, y la proporción de usuarios activos sin wearable, que es el 65% del segmento y el que queda afuera cuando la categoría asume que el usuario ya compró un reloj.'),
  p('**Salud y seguridad del usuario.** Una aplicación que indica cuánto entrenar puede empujar a alguien a lesionarse, y el producto toma posición: el coach protege sesiones por fatiga, lesión o enfermedad en lugar de exigir su cumplimiento, y no penaliza el día perdido. Los indicadores son la proporción de sesiones protegidas por esas razones y la adherencia sostenida a doce semanas, que mide si el acompañamiento produce constancia y no abandono. Se deja constancia de que Scala no emite diagnóstico ni indicación médica. **La mujer atleta**, identificada en el Módulo 4 como una variante transversal desatendida porque la planificación sensible al ciclo menstrual casi no existe en la oferta, tiene su propio indicador: la proporción de usuarias con seguimiento del ciclo activado y su retención comparada con la del resto de la base.'),
  p('**Huella ambiental.** Scala es un producto digital sin hardware propio, sin logística ni packaging, así que su huella se concentra en el cómputo. El indicador es el consumo de cómputo por usuario activo y por mes, que ya se mide porque es el costo variable principal: es un caso poco frecuente en el que el incentivo económico y el ambiental apuntan en la misma dirección, porque cada mejora de eficiencia reduce a la vez el costo y la energía por usuario. No se declara una meta de reducción porque todavía no hay línea de base con usuarios pagos.'),

  S('8. Conclusión: la lógica general del negocio'),
  p('Scala es un negocio de suscripción con costo marginal bajo. Cada suscriptor deja un margen bruto estimado del 62% cuando paga él y del 71% cuando lo paga su entrenador, positivo incluso en el escenario de uso más intensivo, y el punto de equilibrio se mide en cientos de suscriptores y no en decenas de miles. El precio al atleta tiene evidencia de comportamiento, porque casi nadie abandonó al leerlo, y el precio al entrenador tiene evidencia de mercado, porque es el que ya paga en otras plataformas.'),
  p('La decisión estructural que agrega este módulo es que **el entrenador entra como canal de distribución y de cobro, y no como un segundo cliente ni como un segundo modelo de ingresos**. El atleta sigue siendo el único beneficiario del producto y la unidad de ingreso sigue siendo la misma; lo único que cambia es quién firma la factura, y se decidió que la firme el entrenador para que el atleta no tenga que pagar dos veces por la misma semana de entrenamiento.'),
  p('El modelo funciona si se cumplen tres condiciones que todavía hay que probar: que el costo de inferencia por usuario se quede donde lo estimamos; que la distribución deje de depender de la red personal de los fundadores, condición que a diferencia de la versión anterior ya tiene plan y experimento diseñado en el canal del entrenador y las tres entrevistas de la Sección 3.4; y que los que prueban paguen y se queden, lo que sólo va a medir el cobro real sobre las primeras cohortes.'),
  p('A esas tres se suma un riesgo que trae la decisión de canal y que es de producto, no de mercado: **hasta que exista la superficie que le permite al entrenador ver y aprobar el trabajo de su cartera, Scala se suma a lo que él ya paga en vez de reemplazarlo**. Pedirle a un profesional que gana US$47.000 al año que sostenga dos plataformas a la vez es una venta difícil, de modo que construir esa superficie es la precondición del canal y no un agregado posterior. Sobre estas condiciones se apoya lo que sigue: el tamaño de mercado, la proyección de ventas y costos y los unit economics completos, que son materia del Módulo 7.'),

  S('Anexo A · Declaración de uso de inteligencia artificial'),
  p('En línea con las pautas de la Maestría, se detallan a continuación las herramientas de inteligencia artificial empleadas en este trabajo, el propósito de su uso y la forma en que interactuamos con ellas.'),

  T('Herramientas utilizadas'),
  p('Para elaborar este trabajo se hizo uso de Claude, de Anthropic, como espacio de trabajo compartido donde se centralizó el contexto del proyecto: los documentos de los módulos anteriores, el modelo de unit economics del Documento 3 y los resultados del experimento del Módulo 5. Para la investigación de la Sección 3.3 y de la Sección 5 se usó además su capacidad de búsqueda web.'),

  T('Motivación'),
  p('El propósito principal fue sostener la coherencia entre los nueve bloques del canvas y la trazabilidad de cada número del entregable. El margen bruto y el punto de equilibrio se recalcularon a partir de los supuestos del Documento 3, y cada cifra de evidencia se contrastó con los registros del Módulo 5, para que ningún número quedara separado de su fuente. En esta segunda iteración se sumó un objetivo adicional: verificar contra fuentes externas los supuestos sobre el canal del entrenador, en lugar de escribirlos como intuición del equipo.'),

  T('Uso reflexivo y enfoque dialógico'),
  p('La interacción fue la de un copiloto de pensamiento y no la de un generador pasivo de texto: se usó para ordenar las consignas, revisar la coherencia del canvas bloque por bloque, buscar y contrastar evidencia externa, y producir primeros borradores que luego fueron revisados y reescritos. Las decisiones sobre el modelo, la interpretación de la evidencia y la redacción final son nuestra responsabilidad. En particular, **la decisión de que el entrenador sea quien pague la suscripción de sus atletas fue del equipo y corrigió una recomendación previa de la herramienta**, que proponía que el atleta pagara en los dos canales.'),
  p('A modo de ejemplo, algunas de las instrucciones dirigidas que se utilizaron fueron:'),
  p('_Recorré el canvas de derecha a izquierda y marcá cada elemento huérfano: segmentos sin propuesta, propuestas sin actividad o recurso, aliados o actividades sin costo._'),
  p('_Buscá qué le cobran al entrenador las plataformas del sector y con qué evidencia, y decime si lo que encontrás contradice lo que estamos suponiendo._'),
  p('_Señalá cada afirmación sobre el precio que no se apoye en un dato del Módulo 3, del Módulo 5 o de una fuente citada._'),
];
